# Dockerfile

# Use Node.js to build the app
FROM node:20 AS build

WORKDIR /server

# Clone the repository
RUN git clone https://loic-hpp:glpat-v9Qt8vbw2zoY-stynsRH@gitlab.com/polytechnique-montr-al/inf3995/20243/equipe-107/geppetto.git\
    && cd geppetto\
    && git checkout develop\
    && git pull

WORKDIR /server/geppetto/application/server

# Install dependencies
RUN npm ci

# Expose the port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
